server:
  port: 8080
  contextPath: /mini-project
---
#spring:
#  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
